version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0.0

jobs:
  compile-and-upload-tool:
    parameters:
      os:
        type: string
      tools:
        type: string

    docker:
      - image: cimg/python:3.10

    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true
      - run:
          name: Download "compile_version_upload_s3.sh" script
          # TODO: fix the URL of this script to use main branch when it gets merged
          command: |
            wget https://raw.githubusercontent.com/readthedocs/readthedocs.org/humitos/build-tool-no-upload-production/scripts/compile_version_upload_s3.sh
      - run:
          name: Download Docker image
          command: |
            for DOCKER_IMAGE in "<< parameters.os >>"
            do
              docker pull readthedocs/build:$DOCKER_IMAGE
              DOCKER_TAG=$(echo << parameters.os >> | cut -d- -f1,2)
              docker tag readthedocs/build:$DOCKER_IMAGE readthedocs/build:$DOCKER_TAG
            done
      - run:
          name: Compile tool version
          command: |
            export OS=$(echo << parameters.os >> | cut -d- -f1,2)

            for TOOL_VERSION in "<< parameters.tools >>"
            do
              export TOOL=$(echo $TOOL_VERSION | cut -d- -f1)
              export VERSION=$(echo $TOOL_VERSION | cut -d- -f2)

              /bin/bash compile_version_upload_s3.sh $TOOL $VERSION
            done
      - aws-s3/sync:
          aws-region: ORG_AWS_REGION
          aws-access-key-id: ORG_AWS_ACCESS_KEY_ID
          aws-secret-access-key: ORG_AWS_SECRET_ACCESS_KEY
          from: ./
          to: s3://${ORG_AWS_BUCKET_NAME}
      - aws-s3/sync:
          aws-region: COM_AWS_REGION
          aws-access-key-id: COM_AWS_ACCESS_KEY_ID
          aws-secret-access-key: COM_AWS_SECRET_ACCESS_KEY
          from: ./
          to: s3://${COM_AWS_BUCKET_NAME}

  tests:
    docker:
      - image: cimg/python:3.10
        environment:
          PIPENV_VENV_IN_PROJECT=1
          PIPENV_IGNORE_VIRTUALENVS=1
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
          docker_layer_caching: true
      - run:
          name: Setup
          command: |
            pip install pipenv
            pipenv install
      - run:
          name: Build Docker image
          command: docker build -t readthedocs/build:ubuntu-22.04 .
      - run:
          name: Run tests
          command: pipenv run pytest


workflows:
  version: 2
  tests:
    jobs:
      - tests

  compile-and-upload-tool:
    jobs:
      - compile-and-upload-tool:
          filters:
            branches:
              # TODO: uncomment when ready to go to prod
              # only: /main/
              only: /humitos/automate-compile-upload-s3/

          # These parameters come from `readthedocs.settings.base`'s
          # RTD_DOCKER_BUILD_SETTINGS variable
          # https://github.com/readthedocs/readthedocs.org/blob/ccdad233cda5bcd3ac3acd935536c9e8cfc2e440/readthedocs/settings/base.py#L536
          #
          # NOTE: update "parameters.os" when we release a new dated Ubuntu image
          # NOTE: update "parameters.tools" when we add a new tool version
          os: "ubuntu-22.04-2022.03.15 ubuntu-20.04-2022.02.16"
          tools: "python-2.7.18 python-3.6.15 python-2.7.18 python-3.6.15 python-3.7.12 python-3.8.12 python-3.9.7 python-3.10.0 python-pypy3.7-7.3.5 python-miniconda3-4.7.12 python-mambaforge-4.10.3-10 nodejs-14.17.6 nodejs-16.9.1 rust-1.55.0 golang-1.17.1"
